spring:
  profiles: dev
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: none
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_customers
    username: custdbuser
    password: CustomersDbPassword
name: dev-YAML
environment: dev

